plugins {
    id 'com.android.application'
}

android {
    namespace 'net.pgaskin.batterytile'
    compileSdk 33

    defaultConfig {
        applicationId "net.pgaskin.batterytile"
        minSdk 31
        targetSdk 33
        versionCode 2
        versionName "2"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
            // ensure the git state doesn't affect the build reproducibility
            vcsInfo.include = false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
}

// pin the toolchain for reproducible builds (and match f-droid and github
// actions)
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

dependencies {
    implementation 'org.lsposed.hiddenapibypass:hiddenapibypass:4.3'
}
